[/]
auto-update-cinnamon-spices=true
auto-update-flatpaks=true
autorefresh-days=3
autorefresh-hours=0
hide-kernel-update-warning=true
hide-systray=true
hide-window-after-update=true
install-last-run=1775175265
refresh-last-run=1774973608
refresh-minutes=10
show-origin-column=true
show-size-column=true
show-welcome-page=false
tracker-grace-period=15
tracker-max-age=7
tracker-max-days=3
window-height=688
window-pane-position=549
window-width=1152
