"$schema" = 'https://starship.rs/config-schema.json'

palette = "bar_colors"

format = """
$hostname\
$username\
$nix_shell\

[](bg:bar2 fg:bar1)\
$directory\
${custom.dir_stack}\

${custom.fix_arrow}\

$git_branch\
$git_status\

$time\
$jobs\
[ ](fg:bar4)\
$line_break\
$character"""

[custom.fix_arrow]
when = "test ! -d .git && ! git rev-parse --is-inside-work-tree > /dev/null 2>&1"
command = "echo "
style = "fg:bar2 bg:bar4"
format = "[$output]($style)"

[custom.dir_stack]
when = "test ! $(cat $SESSION_DIR/$STARSHIP_SESSION) = '1'"
command = "echo  "
style = "bg:bar2 fg:black"
format = "[$output  ]($style)"

[hostname]
ssh_symbol = "󰢹 "
style = "bg:bar1 fg:black"
format = "[ $ssh_symbol]($style)"

[username]
show_always = true
style_user = "bg:bar1 fg:black"
style_root = "bg:bar1 fg:red"
format = '[ $user ]($style)'

[nix_shell]
symbol = "󱄅 "
style = "bg:bar1 fg:black"
format = "[$symbol]($style)"

[directory]
style = "bg:bar2 fg:black"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = " "
style = "fg:black bg:bar3"
format = '[](fg:bar2 bg:bar3)[ $symbol $branch ]($style)'

[git_status]
style = "fg:black bg:bar3"
format = '[($all_status$ahead_behind )]($style)[](fg:bar3 bg:bar4)'
ahead = " 󰁞 ${count}"
behind = " 󰁆 ${count}"
modified = ""
diverged = " 󰁞 ${ahead_count} 󰁆 ${behind_count}"

[time]
disabled = false
time_format = "%l:%M"
style = "fg:black bg:bar4"
format = '[ $time ]($style)'

[jobs]
symbol = ""
style = "fg:black bg:bar4"
format = "[$symbol$number ]($style)"

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'

[palettes.bar_colors]
bar1 = "green"
bar2 = "purple"
bar3 = "yellow"
bar4 = "blue"
