"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](red)\
$username\

[](bg:peach fg:red)\
$directory\

${custom.fix_arrow}\

$git_branch\
$git_status\

$time\
[ ](fg:green)\
$line_break\
$character"""

palette = 'catppuccin_mocha'

[custom.fix_arrow]
when = "test ! -d .git && ! git rev-parse --is-inside-work-tree > /dev/null 2>&1"
command = "echo "
style = "fg:peach bg:green"
shell = ["bash"]
format = "[$output]($style)"
disabled = false

[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = '[ $user ]($style)'

[directory]
style = "bg:peach fg:crust"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:yellow"
format = '[](bg:yellow fg:peach)[[ $symbol $branch ](fg:crust bg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status $ahead_behind )](fg:crust bg:yellow)]($style)[](fg:yellow bg:green)'
ahead = "󰁞 ${count}"
behind = "󰁆 ${count}"
modified = ""
diverged = "󰁞 ${ahead_count} 󰁆 ${behind_count}"

[time]
disabled = false
time_format = "%l:%M"
style = "bg:green"
format = '[[  $time ](fg:crust bg:green)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
