[plugins]
active-plugins=['smartspaces', 'textsize', 'spell', 'sort', 'quickhighlight', 'filebrowser', 'codecomment']

[preferences/editor]
display-right-margin=true
editor-font='SauceCodePro Nerd Font 11'
insert-spaces=true
right-margin-position=uint32 120
style-scheme-for-light-theme-variant='solarized-light'
tabs-size=uint32 2
use-default-font=false
wrap-last-split-mode='word'

[preferences/ui]
bottom-panel-visible=false
side-panel-visible=false
statusbar-visible=true
theme-variant='system'

[state/window]
bottom-panel-size=140
height=700
maximized=true
side-panel-active-page='GeditWindowDocumentsPanel'
side-panel-size=200
size=(422, 1019)
state=87040
width=900
