[/]
accuracy=9
angle-units='degrees'
base=10
button-mode='advanced'
currency-display='name'
number-format='automatic'
refresh-interval=604800
show-thousands=true
show-zeroes=false
source-currency=''
source-units=['degree']
target-currency=''
target-units=['radian']
unit-category='angle'
window-maximized=false
window-position=(867, 218)
window-size=(700, 625)
word-size=64
