flatpak install flathub ca.desrt.dconf-editor -y
flatpak install flathub cc.arduino.IDE2 -y
flatpak install flathub com.discordapp.Discord -y
flatpak install flathub com.freerdp.FreeRDP -y
flatpak install flathub com.github.tchx84.Flatseal -y
flatpak install flathub com.polyphone_soundfonts.polyphone -y
flatpak install flathub com.rustdesk.RustDesk -y
flatpak install flathub com.spotify.Client -y
flatpak install flathub com.tomjwatson.Emote -y
flatpak install flathub fr.handbrake.ghb -y
flatpak install flathub io.github.ilya_zlobintsev.LACT -y
flatpak install flathub io.github.pwr_solaar.solaar -y
flatpak install flathub org.audacityteam.Audacity -y
flatpak install flathub org.bunkus.mkvtoolnix-gui -y
flatpak install flathub org.darktable.Darktable -y
flatpak install flathub org.filezillaproject.Filezilla -y
flatpak install flathub org.fontforge.FontForge -y
flatpak install flathub org.gimp.GIMP -y
flatpak install flathub org.gnome.Snapshot -y
flatpak install flathub org.gnome.World.PikaBackup -y
flatpak install flathub org.inkscape.Inkscape -y
flatpak install flathub org.openscad.OpenSCAD -y
flatpak install flathub org.remmina.Remmina -y
flatpak install flathub org.signal.Signal -y
flatpak install flathub org.videolan.VLC -y
