# Font size + other options configured in OS-specific files
include $KITTY_OS.conf

scrollback_lines 100000
cursor_shape beam

# blur only works on macOS/wayland
background_blur 16

# must be set lower than 1.0 to enable changing transparency one a per-color basis
background_opacity 0.95

# small bit of horizontal padding to prevent text appearing clipped
window_padding_width 2

# map ctrl+enter to open new window (same as ctrl+shift+enter / cmd+enter)
map ctrl+enter new_window

# always render entire underline
underline_exclusion 0

# visual bell
visual_bell_duration 0.5

# max ~30fps
repaint_delay 33

# BEGIN_KITTY_FONTS
font_family      family="UbuntuMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
